config/routes.rb
Tt11::Application.routes.draw do
  resources :forumtalks

  resources :forumthemes

  resources :forumroots

  get "login/add_user"

  get "login/login"

  get "login/logout"

  get "login/index"

  get "login/delete_user"

  get "login/list_users"

  get "export/xls"

  get "forumtalks/del"

  resources :works

  resources :editansws

  resources :editsubjs

  resources :status1s

  resources :office1s

  get "search/index"

  get "sotrud/index"
  get "main/index"
  get "main/about"
  get "main/work"
  get "main/sotrud"
  get "main/album"
  get "main/letter"
  get "desk_subjs/test"
  post "desk_subjs/save_mess"
  post "desk_subjs/new_answ"
  post "desk_subjs/save_answ"
  get "holiday/index"
  post "holiday/days"
  resources :holiday
  resources :desk_subjs

  
  

   root :to => "desk_subjs#index"
   match '/' , :controller => "desk_subjs" , :action => "index"

   match ':controller(/:action(/:id(.:format)))'
end

app/models/forumtalk.rb
class Forumtalk < ActiveRecord::Base
  belongs_to :forumtheme
  belongs_to :office1
end

app/controllers/forumtalks_controller.rb
class ForumtalksController < ApplicationController
  layout 'desk'
  before_filter :adm_authorize , :except => ['index' , 'create']

  def index
    curs
    usr
    @forumtheme = Forumtheme.find(params[:theme])
    if admin?
      @forumtalks = @forumtheme.forumtalk.sort { |a, b| b.created_at <=> a.created_at }
    else
    @forumtalks = @forumtheme.forumtalk.find_all{|m| m.vis }.sort { |a, b| b.created_at <=> a.created_at }
    end
   
    @forumtalk = Forumtalk.new

  end

#  def show
#    redirect_to :action=>'index' , :theme => $back
#  end



  def edit
    curs
    @forumtalk = Forumtalk.find(params[:id])
    @forumtheme = @forumtalk.forumtheme
  end


  def create
    @forumtalk = Forumtalk.new(params[:forumtalk])

    respond_to do |format|
      if @forumtalk.save
        format.html { redirect_to :controller => 'forumtalks' , :action => 'index' , :theme => @forumtalk.forumtheme_id }
        format.xml  { render :xml => @forumtalk, :status => :created, :location => @forumtalk }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @forumtalk.errors, :status => :unprocessable_entity }
      end
    end
  end



  def update
    @forumtalk = Forumtalk.find(params[:id])

    respond_to do |format|
      if @forumtalk.update_attributes(params[:forumtalk])
        format.html { redirect_to(:controller => 'forumtalks' , :theme =>@forumtalk.forumtheme.id) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @forumtalk.errors, :status => :unprocessable_entity }
      end
    end
  end


  def destr
    @forumtalk = Forumtalk.find(params[:id])
    $back = @forumtalk.forumtheme_id
    @forumtalk.destroy

    redirect_to :action=>'index' , :theme => $back
  end
  

end

app/helpers/forumtalks_helper.rb
module ForumtalksHelper
end

app/views/forumtalks/_form.html.erb
<table>
  <tr> <td style="width: 70px" valign="top">
      <% if login? %>
       <%# @user2 = Office1.find_by_id(session[:user_id]) %>
      <div style="width: 70px; height: 70px; background-color: silver; margin-top: 30px; border: 1px solid #b1b3b6;">
        <img src="/images/photo/<%=@usr.pic %>.jpg" width="70px" />
      </div>
<% else %>
      <div style="width: 70px; height: 70px; background-color: silver; margin-top: 30px; border: 1px solid #b1b3b6;  background-image: url(/images/ava/qq.jpg); background-position: center center;">
</div>
<% end %>



    </td>
    <td>
<div id="new_mess" style="  margin-top: 10px; margin-left: 10px">
<%= form_for(@forumtalk) do |f| %>
  <%= f.hidden_field :forumtheme_id , :value => @forumtheme.id %>
  <%= f.hidden_field :office1_id , :value => @usr.id if @usr %>

  <div class="field">
    <%= f.label 'Заголовок: '%>
    <%= f.text_field :title , :style => 'width: 487px;' %>
  </div>
  <div class="field">

    <%= f.cktext_area :content %>
  </div>
<% if admin? %>
  <div class="field">
    <%= f.label 'Видимость' %>
    <%= f.check_box :vis %>
  </div>
<% end %>
  <div class="actions">
    <%= f.submit 'Написать' %>
  </div>
<% end %>



</div>
    </td> </tr>
</table>

app/views/forumtalks/_post.erb
<table class="subj2 <%= 'off' unless @post.vis %> " cellspacing="0" cellpadding="0" style="width: 710px;" >
   <tr>
     <td style="width: 70px; padding: 0px;" valign="top" rowspan="2" >
      <% @user = @post.office1 %>
        <% if @user %>
         <img src="/images/photo/<%= @user.pic%>.jpg" width="70px" />
        <% else %>
        <img src="/images/ava/qq.jpg" width="70px" />
        <% end %>

    </td>
    <td  valign="top"  >


    <div class="ndt"  >
        <span class="name">
             <%= @user.last_name if @user %> <%= @user.name if @user %>
        </span>


      <span class="ddate">
      <%= @post.created_at.strftime("%d")+'.'+ @post.created_at.strftime("%m")+'.'+ @post.created_at.strftime("%Y")%>.
      </span>
<% if admin? %>
  <div style="float: right;">
    <span style="color: red;"> <%='сообщение отключено'  unless @post.vis  %> </span>
 <%= link_to 'Редактировать', edit_forumtalk_path(@post) %> |
 <%= link_to 'Удалить', {:controller => 'forumtalks' ,:action => 'destr' , :id => @post.id} %>
  </div>
<% end %>

      <div class="title"> <%= raw  @post.title %>  </div>
      </div>


        <div class="text"><%= raw  @post.content %> </div>

     </td>
    </tr>

</table>

app/views/forumtalks/_post_t.erb
<table class="subj2" cellspacing="0" cellpadding="0" >
   <tr>
     <td style="width: 70px; padding: 0px;" valign="top" rowspan="2" >
      <% @user = @post.office1 %>
        <% if @user %>
         <img src="/images/photo/<%= @user.pic%>.jpg" width="70px" />
        <% else %>
        <img src="/images/ava/qq.jpg" width="70px" />
        <% end %>

    </td>
    <td style="width:700px;" valign="top"  >


    <div class="ndt"  >
        <span class="name">
             <%= @user.last_name if @user %> <%= @user.name if @user %>
        </span>


      <span class="ddate">
      <%= @post.created_at.strftime("%d")+'.'+ @post.created_at.strftime("%m")+'.'+ @post.created_at.strftime("%Y")%>.
      </span>
<% if admin? %>
  <div style="float: right;">
 <%= link_to 'Редактировать', {:controller=>'forumthemes' , :action => 'edit' , :id => @forumtheme.id , :root => @forumtheme.forumroot_id } %>
  </div>
<% end %>

      <div class="title"> <%= raw  @post.title %>  </div>
      </div>


        <div class="text"><%= raw  @post.content %> </div>

     </td>
    </tr>

</table>

app/views/forumtalks/edit.html.erb
<% content_for(:cont) do %>

<h1>Редактирование сообщения</h1>

<%= render 'form' %>


<%= link_to 'Вернуться', :controller => 'forumtalks' , :theme =>@forumtheme.id %>


<% end %>

app/views/forumtalks/index.html.erb
<% content_for(:cont) do %>
  <h1>Форум Живого офиса</h1>
<div style="width: 730px; ">


  <h1  class="forum_h1">Раздел: <span><%= @forumtheme.forumroot.title %></span>. Тема: <span><%= @forumtheme.title %></span></h1>


 <div class="f_path">
  <%= link_to 'Все разделы' , :controller => 'forumroots'  %> /
       <%= link_to  @forumtheme.forumroot.title, :controller => 'forumthemes' , :id => @forumtheme.forumroot.id %> /
       <%= @forumtheme.title %>

       <form style="display: inline; float: right">
         Перейти:
         <select onchange="redir(this)">
           <% for f_root in Forumroot.find(:all , :conditions => ['vis = ?',1 ]) do %>
           <optgroup label="<%= f_root.title %>:">
             <% @theme = f_root.forumtheme.find_all{|f| f.vis } %>
              <% for theme in @theme do %>
             <option value="/forumtalks?theme=<%=theme.id%>" <%=  'selected="selected"' if theme.id.to_s == params[:theme]%> > <%=theme.title %>  </option>
       
              <% end %>
           </optgroup>
           <% end %>
         </select>
       </form>

</div>


<div class="forumtalk">
 <% @post = @forumtheme %>
<%= render :partial => 'post_t' , :post => @post%>

</div>


<% @forumtalks.each do |forumtalk| %>

  <% @post = forumtalk %>
<div class="forumtalk">
<%= render :partial => 'post' , :post => @post%>
</div>
<% end %>



<div class="new_mess">
  <h2>Новое сообщение </h2>
<%= render :partial =>'form' %>
</div>

</div>
<% end %>