config/routes.rb
Tt11::Application.routes.draw do
  resources :forumtalks

  resources :forumthemes

  resources :forumroots

  get "login/add_user"

  get "login/login"

  get "login/logout"

  get "login/index"

  get "login/delete_user"

  get "login/list_users"

  get "export/xls"

  get "forumtalks/del"

  resources :works

  resources :editansws

  resources :editsubjs

  resources :status1s

  resources :office1s

  get "search/index"

  get "sotrud/index"
  get "main/index"
  get "main/about"
  get "main/work"
  get "main/sotrud"
  get "main/album"
  get "main/letter"
  get "desk_subjs/test"
  post "desk_subjs/save_mess"
  post "desk_subjs/new_answ"
  post "desk_subjs/save_answ"
  get "holiday/index"
  post "holiday/days"
  resources :holiday
  resources :desk_subjs

  
  

   root :to => "desk_subjs#index"
   match '/' , :controller => "desk_subjs" , :action => "index"

   match ':controller(/:action(/:id(.:format)))'
end

app/models/forumroot.rb
class Forumroot < ActiveRecord::Base
  has_many :forumtheme
end

app/controllers/forumroots_controller.rb
class ForumrootsController < ApplicationController
 layout 'desk'

  def index
    curs
    @forumroots = Forumroot.all
   

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @forumroots }
    end
  end


  def new
    curs
    @forumroot = Forumroot.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @forumroot }
    end
  end

  # GET /forumroots/1/edit
  def edit
    curs
    @forumroot = Forumroot.find(params[:id])
  end

  # POST /forumroots
  # POST /forumroots.xml
  def create
    @forumroot = Forumroot.new(params[:forumroot])

    respond_to do |format|
      if @forumroot.save
        format.html { redirect_to(:action=> 'index', :notice => 'Раздел добавлен') }
        format.xml  { render :xml => @forumroot, :status => :created, :location => @forumroot }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @forumroot.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /forumroots/1
  # PUT /forumroots/1.xml
  def update
    @forumroot = Forumroot.find(params[:id])

    respond_to do |format|
      if @forumroot.update_attributes(params[:forumroot])
        format.html { redirect_to(:action=> 'index', :notice => 'Раздел сохранен') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @forumroot.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /forumroots/1
  # DELETE /forumroots/1.xml
  def destr
    @forumroot = Forumroot.find(params[:id])
    @forumroot.destroy

    respond_to do |format|
      format.html { redirect_to(:action => 'index') }
      format.xml  { head :ok }
    end
  end
end

app/helpers/forumroots_helper.rb
module ForumrootsHelper
end

app/views/forumroots/_form.html.erb
<%= form_for(@forumroot) do |f| %>


  <div class="field">
    <%= f.label 'Название' %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label 'Видимый' %>
    <%= f.check_box :vis %>
  </div>
  <div class="actions">
    <%= f.submit 'Сохранить' %>
  </div>
<% end %>

app/views/forumroots/edit.html.erb
<% content_for(:cont) do %>
<div class="f_root">
<h1>Форум Живого офиса</h1>

<%= render 'form' %>


<%= link_to 'Вернуться', forumroots_path %>
</div>

<% end %>

app/views/forumroots/index.html.erb
<% content_for(:cont) do %>
<div class="f_root">

<h1 class="forum_h1">Форум Живого офиса</h1>

<table class="f_root_table" cellpadding="1" cellspacing="1">
  <tbody>
    <tr>
      <th> </th>
      <th width="75%">Раздел форума </th>
      <th width="10%" align="center">Тем </th>
      <th width="10%" align="center">Сообщений </th>
    </tr>
<% @forumroots.each do |forumroot| %>

    <tr style="background-color: <%= cycle('white','#F2EFF6') %>">
      <td> <%= image_tag('/images/folder.gif')  %>  </td>
      <td> <%= link_to forumroot.title ,  {:controller=> 'forumthemes' , :id => forumroot.id  } , :class=>'f_title' %>
        <% if admin? %>
        <div style="float: right;">
        <%='раздел отключен'  unless forumroot.vis  %>
        <%= link_to 'Редактировать', edit_forumroot_path(forumroot) %> | 
        <%= link_to 'Удалить', {:action=>'destr' , :id=>forumroot.id}, :confirm => 'Точно?' %>
        </div>
        <% end %>
      </td>
      <td align="center"> <%= forumroot.forumtheme.find_all{|f| f.vis}.size  %>  </td>
      <td align="center"> <%= forumroot.forumtheme.size + forumroot.forumtheme.inject(0){|r,s| (r + s.forumtalk.find_all{|f| f.vis}.size) }   %>  </td>
  
</tr>
<% end %>


</tbody>
</table>
<%= button_to 'Добавить раздел форума', new_forumroot_path if admin? %>
</div>
<% end %>

app/views/forumroots/new.html.erb
<% content_for(:cont) do %>
<div class="f_root">

<h1>Новый раздел</h1>

<%= render 'form' %>

<%= link_to 'Вернуться', forumroots_path %>
</div>

<% end %>