config/routes.rb
Tt11::Application.routes.draw do
  resources :forumtalks

  resources :forumthemes

  resources :forumroots

  get "login/add_user"

  get "login/login"

  get "login/logout"

  get "login/index"

  get "login/delete_user"

  get "login/list_users"

  get "export/xls"

  get "forumtalks/del"

  resources :works

  resources :editansws

  resources :editsubjs

  resources :status1s

  resources :office1s

  get "search/index"

  get "sotrud/index"
  get "main/index"
  get "main/about"
  get "main/work"
  get "main/sotrud"
  get "main/album"
  get "main/letter"
  get "desk_subjs/test"
  post "desk_subjs/save_mess"
  post "desk_subjs/new_answ"
  post "desk_subjs/save_answ"
  get "holiday/index"
  post "holiday/days"
  resources :holiday
  resources :desk_subjs

  
  

   root :to => "desk_subjs#index"
   match '/' , :controller => "desk_subjs" , :action => "index"

   match ':controller(/:action(/:id(.:format)))'
end

app/views/desk/_n2.html.erb
<div>

  <div id="photo2" style="width: 700px; height: 518px; background-image: url(/images/ava/n_back.gif);
       background-position: center center; background-repeat: no-repeat; ">
    <a href="/desknews/wallpaper"> <img src="/images/wallpaper/oboi1.jpg" /> </a>
   
  </div>
  


</div>

app/views/desk/_n5.html.erb
<div>

  <div id="photo2" style="width: 700px; height: 518px; background-image: url(/images/ava/n_back.gif);
       background-position: center center; background-repeat: no-repeat; ">

<a href="/торты на заказ"> <img src="/images/news/tort.jpg" /> </a>

  </div>



</div>

app/views/desk/_new_subj2.erb
<%= javascript_include_tag :ckeditor %>
<b   class="name"> Новое сообщение </b>
<br/>
<table>
  <tr> <td style="width: 70px" valign="top">
      <% if login? %>
       <%# @user2 = Office1.find_by_id(session[:user_id]) %>
      <div style="width: 70px; height: 70px; background-color: silver; margin-top: 30px; border: 1px solid #b1b3b6;">
        <img src="/images/photo/<%=@usr.pic %>.jpg" width="70px" />
      </div>
<% else %>
      <div style="width: 70px; height: 70px; background-color: silver; margin-top: 30px; border: 1px solid #b1b3b6;  background-image: url(/images/ava/qq.jpg); background-position: center center;">
</div>
<% end %>
   
        

    </td>
    <td>
<div id="new_mess" style="  margin-top: 20px; margin-left: 50px">

<%=  form_for :desk_subj_new, :url=>{:controller=>'desk_subjs' , :action => "save_mess" } do |f|  %>

  <% if login? %>
  <% @usr = Office1.find_by_id(session[:user_id]) %>
  <%= f.hidden_field :user_id , :value=>@usr.id  %>
  <% end %>
   <div class="label2"> Тема сообщения :</div>
   <div class="okno2" >
     <%= f.hidden_field :city , :value=>@usr.city %>
        <%= f.text_area :subj, :cols => 60, :rows=> 1 ,:class=>'tema' %>
   </div>
  <br/>
  <div class="label2"> Ваше сообщение :</div>
  <div  align="left" style="margin-bottom: 15px;">

       <%= f.cktext_area :s_text ,:toolbar=>'Full', :width=>'550px', :height=>'200px'  %>
  </div>


  <a href="#" onclick="zp('newsubj')"  style="float:left;"> Отмена </a>

    <%= f.submit '' , :class =>'new_sub' %>


<% end %>


</div>
    </td> </tr>
</table>

app/views/desk/_pics.html.erb
<img src="<%='/images/news/'+@pname1.img%>" />

app/views/desk/_status.erb
<%
    @status_o=Status1.find :all , :conditions=>['status=? and city=?', 1 , @usr.city]
    @status_b=Status1.find :all , :conditions=>['status=? and city=?', 2 , @usr.city]
    @status_u=Status1.find :all , :conditions=>['status=? and city=?', 3 , @usr.city]

%>


<% if @status_o and @status_o.size != 0%>
<div class="status" >
  <img src="/images/status_01.jpg" />
  <h3> В отпуске </h3>
<% for stat in @status_o do %>
  <p style="margin-bottom: 15px;">
    <span class="name"> <%= stat.name %> </span> <br/>
    <b>На работу:</b> <%= stat.date %>
 <% if stat.subst and stat.subst!='' %>
    <br/>
<span style="font-weight: bold;">замещает:</span> <br/>
<%= stat.subst %>
<% end %>
  </p>
<% end %>
  <img src="/images/vs_35.jpg"/>
</div>
<% end %>



<% if @status_b and @status_b.size != 0%>
<div class="status" >
  <img src="/images/status_02.jpg" />
  <h3> На больничном </h3>
<% for stat in @status_b do %>
  <p style="margin-bottom: 15px;">
    <span class="name"> <%= stat.name %> </span> <br/>
<%= stat.date %> <br/>
<span style="font-weight: bold;">замещает:</span> <br/>
<%= stat.subst %>
  </p>
<% end %>
  <img src="/images/vs_35.jpg"/>
</div>
<% end %>



<% if @status_u and @status_u.size != 0%>
<div class="status" >
  <img src="/images/status_01.jpg" />
  <h3> Благодарим за работу </h3>
<% for stat in @status_u do %>
  <p style="margin-bottom: 15px;">
    <span class="name"> <%= stat.name %> </span> <br/>
<span style="font-weight: bold;">замещает:</span> <br/>
<%= stat.subst %>
  </p>
<% end %>
  <img src="/images/vs_35.jpg"/>
</div>
<% end %>

app/views/desk/aa.html.erb
<% content_for(:cont) do %>
<h1>Editing dAAAAA</h1>

<% end %>

app/views/desk/get.html.erb
<% content_for(:cont) do %>
<%= error_messages_for("picture") %>

<% for pict in @pictures do %>
<br/>
   <%= pict.comment %>
<br/>
  <%= pict.name %>
  <br/>
<img src="<%= url_for(:action =>'picture' , :id => pict.id) %>" /><br/>
   <%=link_to 'Удалить', :action =>'destroy' , :id => pict.id %> <br/><br/>
<% end %>



  <%  form_for(:picture, :url => {:action => 'save'}) do |form|  %>
comment: <%= form.text_field, :comment %>  <br/>
Our image: <%= form.file_field :data %>
<br/>!!!!!!!!!!!!!!!!!!!!!!!!!!!
<%= submit_tag("upload") %>
<% end %>

<% end %>

app/views/desk/index.html.erb
<% content_for(:cont) do %>
  <script type="text/javascript" src="/jq/jquery-1.2.3.js"></script>

<style type="text/css">
 #q_answ_submit {background: transparent ; border: none; color: red; cursor: pointer;  }
  #opros label {font-weight: normal;}
.tp {position:relative;text-indent:0;}
.tp strong {color: red;}
.tp b {
   color:#000;
   cursor:help;
   font-weight:normal;
}
.tp b span {display:none;}
/*-- для FF, OPERA, IE7 --*/
.tp b:hover {

}
.tp b:hover span {
   background: #fdd4b6;
   color:#000;
   display:block;
   padding:7px;
   position:absolute;
   top:2px;
   left:5px;
   z-index:10;
   text-align:left;
   width:250px;

}
.tp img  {width: 70px;   border: 1px solid #b1b3b6;}
.tp i img  {width: 70px;   border: none;}
.tp i  { border: 1px solid #b1b3b6; display:block; width: 70px; height: 70px; overflow: hidden;}
button {background: none; font-size: 12px;  border: none; color: green; position: relative; left: -30px;}
.comments a {color: red;}
</style>

<!--[if IE 6]>
<style type="text/css">
.tp b {behavior:url(hover.htc);}
.tp .hover {

}
.tp .hover span {
   background:#fdd4b6;
   color:#000;
   display:block;
   padding:7px;
   position:absolute;
   top:2px;
   left:5px;
   z-index:10;
   text-align:left;
   width:250px;
}
</style>
<![endif]-->


<div style="position: relative; width: 734px; background: url(/images/vs1_06.jpg) repeat-y top right;" >




<!--
  <div style="margin-left: 100px; margin-bottom: 10px; font-size: 11px; color: #85c441;">
    В меню "мой профиль" Вы сможете выбрать аватарку и внести дополнительную информацию о себе
  </div> <br/>
-->
 <br/><br/>
<div>
  <% if login? %>
  <a href="#" onclick="show_id('newsubj')" style="text-decoration: none; color: red; margin-left: 60px;">
    Написать сообщение</a></div> <br/><br/>
  <% else %>
    <p style="margin-left: 60px; margin-bottom: 30px; color: red">
      Написать сообщение можно после авторизации.
    </p>
  <% end %>

  <div id="newsubj" style="display:none;">
   <%= render :partial=>'new_subj2' %>
  </div>



<% for desk_subj in @desk_subjs %>


    

<table class="subj" cellspacing="0" cellpadding="0" >
   <tr>
     <td style="width: 70px; padding: 0px;" valign="top" rowspan="2" >

        <% if desk_subj.user_id %>
       <% @user = Office1.find_by_id(desk_subj.user_id) %>
            <% if @user %>
        <img src="/images/photo/<%=@user.pic %>.jpg" width="70px" />
             <% else %>
              <img src="/images/ava/qq.jpg" width="70px" />
             <% end %>
        <% else %>
        <img src="/images/ava/qq.jpg" width="70px" />
        <% end %>

    </td>
    <td style="width:700px;" valign="top"  >


    <div class="ndt"  >
        <span class="name">
            <% if desk_subj.user_id %>
       <% @user = Office1.find_by_id(desk_subj.user_id) %>
          <% if @user %>
       <%= @user.last_name + ' ' + @user.name %>
          <% end %>
        <% end %>
        </span>


      <span class="ddate">
      <%= desk_subj.created_at.strftime("%d")+'.'+ desk_subj.created_at.strftime("%m")+'.'+ desk_subj.created_at.strftime("%Y")%>.
      </span>


      <div class="title"> <%= raw  desk_subj.subj %> &nbsp; </div>
      </div>

        <div class="text"><%= raw  desk_subj.s_text %> </div>

     </td>
    </tr>


  <tr>
<!--  +++++++++++++++++++++++++++++ комментарии к сообщениям ++++++++++++++++++++++++++++++++++++++ -->
    <td style="width:100%" >

      <div id="<%='desk_answ_' + desk_subj.id.to_s%>" >
   <script type="text/javascript">
     jq=jQuery.noConflict();
  jq(document).ready(function(){

    jq("#<%='d_' + desk_subj.id.to_s%>").click(function () {
      jq("#<%='desk_answ_' + desk_subj.id.to_s%>").slideToggle("slow");
    });

  });
  </script>

     <table  class="answ" style="display: inherit;"  cellspacing="0" cellpadding="0" >
    <% desk_subj.desk_answ.each do |t| %>
       


          <tr style="display: inherit; margin-bottom: 10px; ">
             <td style="width: 70px; height: 80px; padding: 0px; display: inherit; padding-bottom: 10px;" valign="top"  >
                                 <% if t.user_id %>
               <% @user = Office1.find_by_id(t.user_id) %>
        <img src="/images/photo/<%=@user.pic %>.jpg" width="70px" />
        <% else %>
        <img src="/images/ava/qq.jpg" width="70px" />
        <% end %>
                 </td>
            <td style="width:500px;" >
              <div class="ndt" >
     <span class="name">
            <% if t.user_id %>
       <% @user = Office1.find_by_id(t.user_id) %>
       <%= @user.last_name + ' ' + @user.name %>

        <% end %>
        </span>
              <span class="ddate" >

              <%= t.created_at.strftime("%d")+'.'+t.created_at.strftime("%m")+'.'+t.created_at.strftime("%Y") %>

              </span>
              </div>

              <div class="text" style=" padding-bottom: 10px;" >
           <%=raw t.a_text%>

              </div>
             </td>


          </tr>
          <% end %>
        </table>

      </div>
        <% if desk_subj.desk_answ.size == 0 %>
        <%else%>
       <button id="<%='d_' + desk_subj.id.to_s%>">свернуть/развернуть ответы</button> <br/>
       <%end%>


        <span class="comments" style="float:right; ">

     <% if login? %>
   <%#=  link_to'Добавить комментарий', {:action => 'new_answ', :id=>desk_subj.id}, :remote=>true  %>
 <% @desk_subj_id=DeskSubj2.find(desk_subj.id) %>
 <a  onclick="show_id('<%='a'+@desk_subj_id.id.to_s%>')" style="cursor: pointer;" >
 Добавить комментарий
</a>

 <% else %>
    <span style="color: #999999">
      Добавить комментарий можно после авторизации.
    </span>
  <% end %>
      </span> 
       
       
       <br/>

        <%= render :partial=>'/desk/new_answ' %>


    </td>
<!--  +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->
  </tr>
  </table>

      <% end %>


<br />



<br/>

<%= render :partial=>'/desk/new_subj' %>



</div>
<%end%>

app/views/desk/new.html.erb
<h1>New desk_subj</h1>

<% form_for(@desk_subj) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :subj %><br />
    <%= f.text_area :subj %>
  </p>
  <p>
    <%= f.label :s_text %><br />
    <%= f.text_area :s_text %>
  </p>
  <p>
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </p>
  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', desk_subjs_path %>

app/views/desk/new_answ.js.erb
$("#qq").html("<%= escape_javascript(render :partial => "new_answ") %>");

app/views/desk/pic.html.erb
<br />
<h4>Загрузить фотографию.</h4>
<%= link_to 'Загрузить фото на сайт', :controller=>'picture',:action=>'get' %>
<br>

<%= link_to 'Удаление фото с сайта', :controller=>'pictue',:action=>'index' %>

app/views/desk/show.html.erb
<p>
  <b>Subj:</b>
  <%=h @desk_subj.subj %>
</p>

<p>
  <b>S text:</b>
  <%=h @desk_subj.s_text %>
</p>

<p>
  <b>User:</b>
  <%=h @desk_subj.user_id %>
</p>


<%= link_to 'Edit', edit_desk_subj_path(@desk_subj) %> |
<%= link_to 'Back', desk_subjs_path %>

app/views/desk/test.html.erb
<% content_for(:cont) do %>

          <div class="right_block">
            <div style="margin-bottom: 10px;">
            <% if login? %>
            <%= user_name %>
            <% else %>
            <div id="sitelogin">
            <%= render :partial=>'/part/login' %>
            </div>
            <% end %>
          </div>



          <%= render :partial=>'status' %>
            <img src="/images/vs_19.jpg" width="160px" />
            <%= render :partial=>'/part/newsbox' %>
            <img src="/images/cat.jpg" />
            <br/>
          <br/>
           <img src="/images/vs_35.jpg" />

          </div>



<% end %>

app/views/desk/thanks.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= "thanks.html" %>